services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_fabrica
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - fabrica-network
    depends_on:
      - db


  webserver:
    image: nginx:alpine
    container_name: webserver_fabrica
    restart: unless-stopped
    volumes:
      - .:/var/www
      - ./nginx:/etc/nginx/conf.d/
    networks:
      - fabrica-network
    depends_on:
      - app
    labels:

      - "traefik.http.routers.app.rule=HostRegexp(`{subdomain:[a-z0-9-]+}.localhost`) || Host(`localhost`)"
      - "traefik.http.routers.app.entrypoints=web"
      - "traefik.http.services.app.loadbalancer.server.port=80"

  db:
    image: mysql:8.0
    container_name: db_fabrica
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: multitenant_central
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: eduarda
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - fabrica-network

  proxy:
    image: traefik:v2.9
    container_name: proxy_fabrica
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "8081:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - fabrica-network

networks:
  fabrica-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
